### ISSUE TITLE
[!] Some Other error in adding

### ISSUE THREAD

**Issue by OEDOARDO** [DenizShabani/telegramscraper#2]
Getting this error when i try to adding members... all fine on gather and login. How i can fix that?

**Comment by CyberWolfXD** [comment]
import requests
ModuleNotFoundError: No module named 'requests'

how to fix this ?

**Comment by DenizShabani** [comment]
@OEDOARDO try adding by username. adding by ID is still causing some issues for some people

**Comment by DenizShabani** [comment]
@CyberWolfXD please read the README.md file carefully. You need to install the requirements.
